### ISSUE TITLE
Problems using VSTS authenticated package feeds in a VSTS hosted build

### ISSUE THREAD

**Issue by hcoona** [CommonBuildToolset/CBT.Core#100]
I referenced a package from VSO feeds in my projects. Although I enabled "Allow scripts to access OAuth token", I cannot get it built with CBT.

**Comment by jeffkl** [comment]
You will need to use the VSTS credential provider bundle.

https://docs.microsoft.com/en-us/vsts/package/nuget/nuget-exe

Check in `NuGet.exe` and `CredentialProvider.VSS.exe` to `.build\local\NuGet`

In `.build\local\Extensions\before.build.props` set `CBTModuleRestoreCommand`:

```xml
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <MSBuildAllProjects>$(MSBuildAllProjects);$(MSBuildThisFileFullPath)</MSBuildAllProjects>
    <CBTModuleRestoreCommand>$(CBTLocalPath)\NuGet\NuGet.exe</CBTModuleRestoreCommand>
  </PropertyGroup>
</Project>
```

This will tell CBT to use the checked in NuGet.exe and the credential provider will request an auth token when querying the authenticated VSTS feeds.

**Comment by hcoona** [comment]
VSO NuGet task could use the OAuth token automatically. Is it possible for CBT to use it? I'm not sure whether it a good idea checking in credential provider into the repo.

**Comment by jeffkl** [comment]
The credential provider is only good for local builds by real people.  It gets an auth token and prompts you if necessary.  When doing builds in VSTS, the credential provider does not work.

The VSTS NuGet task can only get auth tokens for feeds on the same account and has other limitations.  I've spoken to the NuGet and VSTS packaging teams about how to unify authentication but I'm not sure if we've made any traction.  

CBT executes NuGet.exe to do the restoration which will not currently work in VSTS unless you have a task that places an auth token into your NuGet.config.  We'll continue to work with the VSTS folks on a better solution

**Comment by hcoona** [comment]
Thanks, this would bring consistent & better user experiments.
