### ISSUE TITLE
Onboarding

### ISSUE THREAD

**Issue by ndrwrbgs** [CommonBuildToolset/CBT.Core#112]
A couple disjoint issues here

- [x] 2.1.1 was released as separate files instead of zip, like the previous versions. Not an issue, but suggests lacking release directions documentation
- [ ] [Getting started](http://commonbuildtoolset.github.io/#/getting-started) mentions a `directory.build.props` file, but that does not exists anywhere and it does not direct on how to create it.
- [ ] [Getting started](http://commonbuildtoolset.github.io/#/getting-started) just cuts off after mentioning folder structure. Should it have a "TODO"/"Pending"/or more information below that for how to actually get started? So far I've downloaded some files and put them in folders, but I doubt that's enough to get started :)

**Comment by jeffkl** [comment]
Thanks for pointing out the error in the latest release, I'll get that in a ZIP file instead.

Our documentation needs a lot of improvement, we've been working on CBT internally at Microsoft and haven't been afforded a lot of time to update the public docs.  

`Directory.Build.props` is a file you must create on your own, more is explained [here](https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build#directorybuildprops-example).  You must be using MSBuild 15+

We'll try and get the public docs updated soon.  Related to #64

**Comment by ndrwrbgs** [comment]
[as an aside - the internal docs pointed me here, and didn't clarify it there either *sad face*]
