### ISSUE TITLE
When CBTModules.proj has bad XML, NuGet swallows the error

### ISSUE THREAD

**Issue by jeffkl** [CommonBuildToolset/CBT.Core#116]
When you have a bad project, MSBuild throws an error but NuGet does not show it:

```
NuGet.exe restore "CBTModules.proj" -NonInteractive  -MSBuildPath "MSBuild\15.0\X86" (In 'd:\dbs\el\offh')
Using Msbuild from 'MSBuild\15.0\X86'.
Nothing to do. This project does not specify any packages for NuGet to restore.
```

We should see if we can bubble the error up to the user.

**Comment by ohadschn** [comment]
I got this with bad `CBTModules.proj` XML which is also bad because it's misleading: 
```
MSBUILD : error : The NuGet restore data file 'C:\Users\ohads\AppData\Local\Temp\fe1113c45de24f81be39a927c8000343.tmp' does not exist.  Ensure that your 'C:\Foo\build\Local\CBTModules\CBTModules.proj' project is using PackageReference elements and that you are using NuGet.exe v4 or later.
```

**Comment by nlyu** [comment]
How do you resolve this?

**Comment by Voskrese** [comment]
https://github.com/CommonBuildToolset/CBT.Core/blob/3681b0a580fe4be0188d8df2573c09e6c33fdd5e/.build/CBT/build.props#L26


OR CBTModules.proj OR packages.config

https://github.com/CommonBuildToolset/CBT.Modules/issues/292#issuecomment-633898591
