### ISSUE TITLE
Hang generating /pp

### ISSUE THREAD

**Issue by kingerja** [CommonBuildToolset/CBT.Core#31]
rd /s/q bin obj
msbuild.exe TfsPowerToolsForPowerShell.psproj  /pp:pp.txt

hangs on 'Create CBT module imports'

However if the obj folder is already there it no-ops the creation of the props files so it doesn't hang.

**Comment by jeffkl** [comment]
Interesting, I couldn't get this to repro on the CBT.Core repository.  Have you tried other repositories?  What modules do you have listed?

**Comment by kingerja** [comment]
Right now I am only listing the CBT.Nuget module.  I might be responsible though for it.  I did an ILmerge of all the dependencies for the cbt.core.dll so it can be used.  (I intend to contribute back a fix so the build of that dll will auto ilmerge in all the dependencies is uses.)

**Comment by jeffkl** [comment]
I'd rather leave the DLL alone and not need to ILMerge anything.  Did you merge in Microsoft.Build.dll and the NuGet stuff?  Were the dependencies not loading correctly?

**Comment by kingerja** [comment]
This hang Still happens when I am using the checked in version of 3.4.3 with cbt.core.dll.  Note this only happens if it pulls down packages during the /pp phase. If a build is done first then packages aren't pulled so things just work.

**Comment by jeffkl** [comment]
Build CBT.Core with symbols
`SET MSBUILDDEBUGONSTART=2`
Run MSBuild.exe
Attache Debugger
Press Enter in command window

**Comment by kingerja** [comment]
So this is the block that causes the hang  ModulePropertyGenerator.cs (around line 87)
            Parallel.ForEach(GetModuleExtensions(), i =>
            {
                ProjectRootElement extensionProject = ProjectRootElement.Create(Path.Combine(extensionsPath, i.Key.Trim()));
                AddImports(extensionProject, properties);
                extensionProject.Save();
            });

If this is replaced to remove the parallel foreach loop. It works...
            foreach (var i in GetModuleExtensions())
            {
                ProjectRootElement extensionProject = ProjectRootElement.Create(Path.Combine(extensionsPath, i.Key.Trim()));
                AddImports(extensionProject, properties);
                extensionProject.Save();
            }


Any idea what may be going on?  Specifically the hang occurs on 
ProjectRootElement extensionProject = ProjectRootElement.Create(Path.Combine(extensionsPath, i.Key.Trim()))
When it is processing usually the last extension in the list I only tried 2 and 3 extensions to see if it was by chance my after.any.targets extension that it was failing on and it isn't.

Anyway let me know if you have any ideas of why the parallel loop fails on that msbuild Create method.   If you want a repro let me know I can see if I can create one a different machine with my changeset.  I didn't dig into the msbuild source to see what exactly is happening.
