### ISSUE TITLE
cbt.core.dll requires specific version of nuget

### ISSUE THREAD

**Issue by kingerja** [CommonBuildToolset/CBT.Core#33]
I tried using cbt.core.dll with 3.4.5 and 3.5 and each failed with various errors.  The only version of nuget that worked was 3.4.3 the version it was built against.

This causes a problem as many times nuget is unstable and I need to checkin a specific version for that specific codebase due to some scenario they have which only works in one version of nuget.

**Comment by jeffkl** [comment]
I found another issue where Visual Studio loads its own version of NuGet into the app domain and can break the `RestoreModules` task.  I think I'll make the task load in a separate app domain.

**Comment by kingerja** [comment]
Come to think of it we have seen issues before in past systems where the default app domain gets something loaded and this causes obscure breaks down the line.  It would probably be a good practice that we do our best to pollute the default app domain as minimally as possible to avoid these issues.

**Comment by kingerja** [comment]
Would it be possible to have a Required properties Item or just a required properties ; list as a property that would state something generic like.
X property is a required property and has not been set...
This way we can easily control the list and others could extend it by adding it to the list.

**Comment by jeffkl** [comment]
> Would it be possible to have a Required properties Item or just a required properties

Anything is possible, did you mean to put this under #6 ?

**Comment by kingerja** [comment]
Yup my bad.  must of had two windows open and not paying attention.

On Dec 6, 2016 5:55 PM, Jeff Kluge <notifications@github.com> wrote:

Would it be possible to have a Required properties Item or just a required properties

Anything is possible, did you mean to put this under #6<https://github.com/CommonBuildToolset/CBT.Core/issues/6> ?

**Comment by josemesona** [comment]
Okay I finally got to the bottom of this.

This commit in NuGet internalized everything during ILMerge: https://github.com/NuGet/NuGet.Client/commit/6c64500be50ada20f39319271402d90b356116fa#diff-aceb12561cec7a1da6166dd1739177b2R632

Then they reversed it (as they should have) here: https://github.com/NuGet/NuGet.Client/commit/a3c9be542f0e7758b2c1a5e38f2cdf1592a8599a#diff-aceb12561cec7a1da6166dd1739177b2L1107

However, NuGet 3.5 shipped in between so it has everything marked as internal.  We need to follow-up with them and get a version 3.5.1 without everything being internal

**Comment by jeffkl** [comment]
Fixed in e60f12ecd7296b1f30f74da317e175965350661f
