### ISSUE TITLE
Can't control import order of cbt modules when using project.json

### ISSUE THREAD

**Issue by kingerja** [CommonBuildToolset/CBT.Core#40]
Project.Json
```json
    "CBT.NuGet": "1.0.5-GPbeta",
    "CBT.Microsoft.Common.Targets": "1.0.0",
    "ILMerge.MSBuild.DPG": "1.0.0-beta",
    "CBT.After.Any.Targets": "1.0.0",
```
Generated imports
```xml
  <Import Project="$(CBTModule_CBT_After_Any_Targets)\CBT\Module\$(MSBuildThisFile)" Condition="Exists('$(CBTModule_CBT_After_Any_Targets)\CBT\Module\$(MSBuildThisFile)')" />
  <Import Project="$(CBTModule_CBT_Microsoft_Common_Targets)\CBT\Module\$(MSBuildThisFile)" Condition="Exists('$(CBTModule_CBT_Microsoft_Common_Targets)\CBT\Module\$(MSBuildThisFile)')" />
  <Import Project="$(CBTModule_CBT_NuGet)\CBT\Module\$(MSBuildThisFile)" Condition="Exists('$(CBTModule_CBT_NuGet)\CBT\Module\$(MSBuildThisFile)')" />
  <Import Project="$(CBTModule_CBT_Traversal)\CBT\Module\$(MSBuildThisFile)" Condition="Exists('$(CBTModule_CBT_Traversal)\CBT\Module\$(MSBuildThisFile)')" />
  <Import Project="$(CBTModule_ILMerge)\CBT\Module\$(MSBuildThisFile)" Condition="Exists('$(CBTModule_ILMerge)\CBT\Module\$(MSBuildThisFile)')" />
  <Import Project="$(CBTModule_ILMerge_MSBuild_DPG)\CBT\Module\$(MSBuildThisFile)" Condition="Exists('$(CBTModule_ILMerge_MSBuild_DPG)\CBT\Module\$(MSBuildThisFile)')" />
```

There are two issues here.
1.  targets import order is really important in msbuild we need a way to control this.  I suggest based off the order they are listed in the project.json file.  
2.  automatically generating the imports for the transitive closure makes it impossible for the user to specify if a module should be imported or not if it is referenced in some other module.  For auto importing it should be required that an entry is in the project.json even if it is technically redundant.

Unless you have a better way we can reason about import order and when something is imported as a module or not.

**Comment by kingerja** [comment]
I am guessing this is related to the forming up of the 
CBTAllModulePaths property

**Comment by jeffkl** [comment]
I couldn't find a way to get the order of the packages defined in the project.json of of the project.lock.json. I was told today that NuGet can do it when it creates the project.nuget.props so that might be promising. Respecting the order in project.json would be good and respecting dependency order would be icing on the cake. 

We could at least crack own project.json to get the user specified order. I'll try to look into this tomorrow...

**Comment by kingerja** [comment]
The big issue is input order needs to be configurable.  no matter where it is.  A very common scenario in msbuild is to inject something into the input order to override specific behavior.  With out this it becomes very hard to target a specific import injection with out all the imports getting shuffled bringing about a completely separate build experience.

**Comment by jeffkl** [comment]
For the record, I agree 😊. I couldn't quickly figure out a way to respect ordering when I added project.json support and forgot to open an issue.

**Comment by kingerja** [comment]
cool. then we will just figure something out.  :)

**Comment by jeffkl** [comment]
Let's look into reading the lock file for ordering which I've been told is correct

**Comment by kingerja** [comment]
I am thinking we can address this in
https://github.com/CommonBuildToolset/CBT.Modules/issues/44

Basically I don't think we should care about ordering of the packages file.  Instead we should have the author of the module specify their ordering requirements in the module.config per import.  Or if not specified then fall back to respecting the package file ordering.

This will give much more power to modules as they can now use ordering overrides for their imports for better control of injection instead of needing to write multiple modules simply because you need some imports before one module and other imports after another module.

**Comment by kingerja** [comment]
Project.json support for this has been cut as project.json support is deprecated.  Perhaps if there is demand in the future for this we will re-evaluate but as last discussed we will only support packages.config and <packagereference  for cbt modules.
