### ISSUE TITLE
Module restore in vs2013 failed with the following error

### ISSUE THREAD

**Issue by kingerja** [CommonBuildToolset/CBT.Core#42]
26>------ Rebuild All started: Project: MyDatabaseProject, Configuration: Debug x64 ------
26>e:\tfs\IS\ES\M2\.build\CBT\build.props(97,5): Error:  MSB4127: The "RestoreModules" task could not be instantiated from the assembly "e:\tfs\IS\ES\M2\.build\CBT\CBT.Core.dll". Please verify the task assembly has been built using the same version of the Microsoft.Build.Framework assembly as the one installed on your computer and that your host application is not missing a binding redirect for Microsoft.Build.Framework. Unable to cast object of type 'CBT.Core.Tasks.RestoreModules' to type 'Microsoft.Build.Framework.ITask'.
26>e:\tfs\IS\ES\M2\.build\CBT\build.props(97,5): Error:  MSB4060: The "RestoreModules" task has been declared or used incorrectly, or failed during construction. Check the spelling of the task name and the assembly name.
26>Done building project "MyDatabaseProject.sqlproj" -- FAILED.

This appears to work fine with the ilmerged version of cbt.core.dll
(*Note this may be fixed by the other bug #33)

**Comment by jeffkl** [comment]
Visual Studio's app.config should redirect MSBuild 14.0 to MSBuild 12.0 and this should just work.  Can you try from a command-line by running MSBuild 12.0:

`MSBuild.exe /t:RestoreModules`

`msbuild.exe.config` has redirects so it should work but so should `devenv.exe.config`...

**Comment by jeffkl** [comment]
This should be fixed by e60f12ecd7296b1f30f74da317e175965350661f, re-open if it repros.
