### ISSUE TITLE
Module doesn't restore in VS before build

### ISSUE THREAD

**Issue by kingerja** [CommonBuildToolset/CBT.Core#43]
When I rd a module folder from the \nugetpackages as well as the obj folder and then I rebuild in VS.  The module restore does not occur before projects are built.  They are still restored just not in time.  The second rebuild works fine.

this is using VS2013 with an old ilmerged version of cbt.core.dll that I have.

**Comment by jeffkl** [comment]
I've hit this before and I'm not sure what to do.  Do we really need to compensate for users deleting packages?  It seems like an uncommon case...

**Comment by kingerja** [comment]
this is about supporting the nuget clear caches scenario.  I think that is an important scenario given that it is a basic nuget troubleshooting step.
