### ISSUE TITLE
Need additional arguments for restore command

### ISSUE THREAD

**Issue by kingerja** [CommonBuildToolset/CBT.Core#44]
Basically I purpose we should add this line after CBTModuleRestoreCommandArguments is defined.
    &lt;CBTModuleRestoreCommandArguments Condition=" '$(CBTModuleRestoreCommandAdditionalArguments)' != '' "&gt;$(CBTModuleRestoreCommandArguments) $(CBTModuleRestoreCommandAdditionalArguments)&lt;/CBTModuleRestoreCommandArguments&gt;

**Comment by kingerja** [comment]
reminder that when we close on this that I will need to update this repo.
ECS_Tickets

**Comment by jeffkl** [comment]
Go ahead and add it.
