### ISSUE TITLE
Support .NET Core

### ISSUE THREAD

**Issue by jeffkl** [CommonBuildToolset/CBT.Core#50]
I figured out how to make CBT work on .NET Core:

```
$(CBTCoreAssemblyPath
  .GetType()
  .Assembly
  .GetType('System.Runtime.Loader.AssemblyLoadContext')
  .GetProperty('Default')
  .GetValue(null)
  .LoadFromAssemblyPath($(CBTCoreAssemblyPath))
  .CreateInstance($(CBTModuleRestoreTaskName))
  .Execute(...))
```

- [x] Remove platform specific directory separators (#49)
- [ ] Port CBT.Core.dll to target `netstandard1.5`
- [ ] Add conditions in `build.props` for `MSBuildRuntimeType=Core`
- [ ] Call `dotnet restore` instead of `nuget restore`
- [ ] Support for module config to be a `.proj` with `<PackageReference />`

**Comment by Porges** [comment]
Another thing to check is using new-style .csproj but targetting Framework. At the moment this doesn't work since the restore isn't run (but I think `dotnet restore` in your list will fix it).

**Comment by hcoona** [comment]
@jeffkl Any progress on this?

**Comment by jeffkl** [comment]
I am working on baking CBT Core directly into MSBuild.

https://github.com/Microsoft/msbuild/pull/2414
https://github.com/Microsoft/msbuild/pull/2014
https://github.com/Microsoft/msbuild/pull/751
https://github.com/Microsoft/msbuild/issues/2278

When MSBuild can restore NuGet packages out of the box prior to building, CBT will become a set of packages.  And since MSBuild is already cross platform, we'll get .NET Core support for free.

**Comment by hcoona** [comment]
Do we have an umbrella item to help track all necessary items? Do we have a milestone for it (targeting MSBuild version)?

**Comment by jeffkl** [comment]
I don't have an issue for tracking it but we plan having it in the next release of MSBuild.

**Comment by Porges** [comment]
Looks like ¾ of those issues are resolved :) Is the SDK resolver the only outstanding missing piece?

**Comment by heartlocker** [comment]
What is the statues of this issue?

**Comment by alburgin** [comment]
Ditto what is the status of this?

**Comment by paeppers** [comment]
What is the status of this
