### ISSUE TITLE
Cause an error if EnlistmentRoot isn't set

### ISSUE THREAD

**Issue by josemesona** [CommonBuildToolset/CBT.Core#6]
We have no good way to stop parsing if a required property isn't set.  We'd have to condition everything and then in the initial target RestoreCBTModules print an error.

**Comment by kingerja** [comment]
I don't know of a good way to stop parsing but you can stop parsing by trying to convert an error message into a Boolean value which will cause an exception message saying "my custom error message. Set this property to fix this exception.." can't be converted to Boolean.

**Comment by jeffkl** [comment]
I found a way to do this via the `InitialTargets` similar to what I did in https://github.com/CommonBuildToolset/CBT.Core/pull/15/files

So the question is, what should the error message be if `EnlistmentRoot` isn't set?

**Comment by kingerja** [comment]
Moving Comment to correct issue.

Would it be possible to have a Required properties Item or just a required properties ; list as a property that would state something generic like.
X property is a required property and has not been set...
This way we can easily control the list and others could extend it by adding it to the list.

**Comment by jeffkl** [comment]
I'm going to close this with #38 and I opened a new issue for this request as #39
