### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by jeffkl** [CommonBuildToolset/CBT.Core#64]
Our documentation needs some love.  Let's improve the getting started and ensure each module is documented.

# Documenting modules
1. Documentation is live on the web with only the latest version available
2. Documentation is somehow hosted in a Git repo so users can view its history
3. Documentation ships inside of NuGet packages

How to documentation release notes

**Comment by zmarty** [comment]
"documentation needs some love" is an understatement.

**Comment by jeffkl** [comment]
I've updated the Getting Started instructions for MSBuild 15.0 and renamed FAQ to Support.

https://github.com/CommonBuildToolset/commonbuildtoolset.github.io/commit/cde138f859d08aaaf669a5c26c791d25c5786834
