### ISSUE TITLE
error MSB4020: The value "" of the "Project" attribute in ele ment <Import> is invalid.

### ISSUE THREAD

**Issue by zmarty** [CommonBuildToolset/CBT.Core#98]
While running init.cmd I started getting this problem: error MSB4020: The value "" of the "Project" attribute in ele ment <Import> is invalid.

It seems to happen when the script is running this command: msbuild /nologo /t:Restore /v:quiet /m dirs.proj 

This problem went away when I deleted this folder: .build\obj

This problem has caused me a lot of wasted time, it would be good if we can improve handling on partial builds or whatever this was.

**Comment by tomuxmon** [comment]
Removing obj folder did not help in my case. Also it only happens when my import statements are in the top. Probably worth mentioning I am trying to build MSI using wix toolset.
